### ISSUE TITLE
最新的SDK能否支持直接定义私钥变量？

### ISSUE THREAD

**Issue by duzhipeng** [PingPlusPlus/pingpp-python#10]
Ping++最新的SDK是用路径参数的方式读取私钥，不知道能否多提供一种配置自定义变量的方式。

**Comment by samurai00** [comment]
你是想直接设置私钥内容吗？ 类似 pingpp.private_key = "-----beginxxx----\nxxxxx\n...." 这样吗？

**Comment by duzhipeng** [comment]
> 你是想直接设置私钥内容吗？ 类似 pingpp.private_key = "-----beginxxx----\nxxxxx\n...." 这样吗？

是的，目前的方式是我直接改了api_requestor.py，将key = private_key_path，不过还是希望官网也提供一下方式，这样以后升级包就不用再去改了。

另外还在这样做的过程中发现另一个问题  #12

**Comment by samurai00** [comment]
好的

**Comment by duzhipeng** [comment]
> 好的

之所以有这样的需求，是因为private_key本身是脱离包的，现在官方是只给路径读文件的方式，而且读文件的逻辑是写在包里的，这样缺乏灵活性了。一般情况下，根据主程序的框架，用户往往需要更灵活的配置方式，就算读文件，相关的逻辑也应该由主程序这边实现，何况其余的几个配置也是直接传变量的，所以不如统一算了。

以上，恳请官方考虑，斟酌实现。
