### ISSUE TITLE
python3.x签名编码兼容性问题

### ISSUE THREAD

**Issue by duzhipeng** [PingPlusPlus/pingpp-python#12]
最新的包（2.0.9）中，在Python3.x下有一处兼容性问题：
在api_requestor.py的def rsa_sign(self, private_key_path, data): 下：

```python
digest = SHA256.new(data)
```
需要改为：
```python
digest = SHA256.new(data.encode('utf-8'))
```
否则会报：

> TypeError: Unicode-objects must be encoded before hashing

**Comment by dylanninin** [comment]
python 3.5 遇到同样问题，`digest = SHA256.new(data.encode('utf-8'))`即可

**Comment by samurai00** [comment]
嗯，这个问题，马上会修复。

**Comment by samurai00** [comment]
2.0.10 版本已修复
