### ISSUE TITLE
无法解析服务器返回的错误信息

### ISSUE THREAD

**Issue by kxxoling** [PingPlusPlus/pingpp-python#13]
因为错误信息中有中文，封装错误信息时一直是 ``UnicodeEncodeError(..., 'ordinal not in range(128)')``。调试的时候非常不方便！

**Comment by samurai00** [comment]
是错误信息是吗，你用的哪个版本？

**Comment by kxxoling** [comment]
python --version 
    Python 2.7.11

**Comment by kxxoling** [comment]
example 里验证密钥的代码也因为同样的问题无法执行。得改成 ``msg = msg.decode('utf-8').encode('utf-8')``。
