### ISSUE TITLE
什么时候对Python3提供支持？

### ISSUE THREAD

**Issue by ghost** [PingPlusPlus/pingpp-python#16]
什么时候对Python3提供支持？

**Comment by samurai00** [comment]
目前就支持的。

**Comment by zhouAndy** [comment]
我去，回得这么快。给力
我现在在服务器（windows2008 r）上面pip install这个包的时候，报了一个错误，如下 ：
running build_ext
warning:GMPor MPIR library not found; Not building Crypto.PublicKey.)_fastmath.
building 'Crypto.Random.OSRNG.winrandom' extension
error: Unable to find vcvarsall.bat
我的环境是python3.5.1, os是64位环境。我想请教下这是缺少什么依赖造成的

**Comment by samurai00** [comment]
http://blog.csdn.net/secretx/article/details/17472107 你看看这个对你有没有帮助

**Comment by zhouAndy** [comment]
多谢，我先看看。

**Comment by zhouAndy** [comment]
看了一下，如果是客户端这个方法是可行的。但是我现在的环境是服务器，硬盘空间有限。要安装一个VS08这种庞然大物，显然是不适合的。还有别的解决方案么？

**Comment by yeahx** [comment]
@zhouAndy 
下载别人编译好的吧。。
http://www.voidspace.org.uk/downloads/pycrypto26/pycrypto-2.6.win-amd64-py3.3.exe
