### ISSUE TITLE
最新alipay要求的更新需要更新这个SDK吗

### ISSUE THREAD

**Issue by wonleing** [PingPlusPlus/pingpp-python#17]
我之前用的python版的pingserver (有一些自己的改动)，html-one的客户端。
请问最新alipay改动中提到的需要更新SDK是指要改新客户端还是更新server端的SDK？
pingpp-python这边的代码需要更新吗

**Comment by samurai00** [comment]
服务端 sdk 不需要更新。如果你想要更新到新的接口，调用 服务端 sdk 时，extra 加一个 new_version 的参数。
