### ISSUE TITLE
创建Charge对象时extra的回调地址是什么地址?和webhooks的回调有什么区别

### ISSUE THREAD

**Issue by jinji-jiangbo** [PingPlusPlus/pingpp-python#18]

**Comment by samurai00** [comment]
extra 里都是同步返回/前端页面跳转的地址。 webhooks 地址是在 dashboard 设置的。

类似的基础问题，请多多查看[API 文档](https://www.pingxx.com/api)、[帮助中心](https://help.pingxx.com/)。也可以在 [社区](https://pub.pingxx.com/) 提问。

**Comment by jinji-jiangbo** [comment]
webhooks 回调我是明白，关键是不明extra这里 跳转用意何在，单纯提示一下用户？

**Comment by samurai00** [comment]
网页类支付时，支付完了，得跳回到你自己的页面，没有这个，用户就只能留在支付宝/银联的页面。那样体验一定是不好的。

**Comment by jinji-jiangbo** [comment]
明白了，tks
