### ISSUE TITLE
关于SDK Webhooks示例代码优化的一点建议

### ISSUE THREAD

**Issue by duzhipeng** [PingPlusPlus/pingpp-python#21]
是这样，SDK里提供了Webhooks的示例代码，对于data部分，是这样进行编码转换的：
`data = data.decode('utf-8') if hasattr(data, "decode") else data`
实际上在本地开发环境，如果不是按照示例代码那样读取本地data文件，而用了其他的请求工具模拟线上请求，上述编码转换方式会导致签名始终不正确。
问题出在data中中文数据这里：
Ping++ 回调Webhooks时，如果json的data里有中文数据，服务端（Python）接收到的数据中文部分是类似以下形式：

> \xe5\xae\x9a\xe5\x88\xb6\xe8\x87\xa

而本地请求工具，同样的data数据，服务端（Python）接收到的数据中文部分是类似以下形式：

> \\u5b9a\\u5236\\u81ea\\u52a8\\u5316\\u670d\\u52a1

示例代码仅能正确处理第一种情况。而第二种情况也很常见（比如curl ）。实际上这就是Python的坑啊～。
总而言之，建议这样处理：

``` Python
def verify(data, sig):
    signs = decode_base64(sig)
    data = data.decode('utf-8') if hasattr(data, "decode") else data
    # 增加的部分
    if '\\u' in data:
        data = data.encode('utf-8').decode('unicode_escape')
    pubkeystr = open(os.path.join(os.path.dirname(__file__),
                     'pingpp_public_key.pem')).read()
    pubkey = RSA.importKey(pubkeystr)
    digest = SHA256.new(data.encode('utf-8'))
    pkcs = PKCS1_v1_5.new(pubkey)
    return pkcs.verify(digest, signs)

希望官方能考虑写进示例代码，有些对Python不熟悉的同学可能因此受益少浪费时间了。

**Comment by duzhipeng** [comment]
对了，说起来你们还用了Crypto这个模块～～然而这个模块并没有Python3版本。

**Comment by michealzh** [comment]
感谢您的建议
