### ISSUE TITLE
小程序支付时，出现“对支付渠道的请求未能成功”提示

### ISSUE THREAD

**Issue by o0starshine0o** [PingPlusPlus/pingpp-python#23]
1、通过小程序接口【wx.login(……）】接口获取到code
2、在服务器端通过【'https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code'】接口获取到openID
3、使用这个openID获取订单时提示【pingpp.error.ChannelError: 对支付渠道的请求未能成功。来自 wx_lite 渠道的错误信息：appid and openid not match】

请问如何解决？

**Comment by samurai00** [comment]
”appid and openid not match” 说明你获取 openid 的 appid（微信的）与你配置在 Ping++ dashboard 的 wx appid 不一致。检查一下两边的渠道参数配置。

**Comment by o0starshine0o** [comment]
是我的商户支付id填写错误，我已经和腾讯那边的工作人员协商更改了，感谢！
