### ISSUE TITLE
quote_from_bytes() expected bytes

### ISSUE THREAD

**Issue by sankyson** [PingPlusPlus/pingpp-python#29]
python3.7 recharge接口调用报错，测试发现提供的sdk内部没有对接收参数进行处理而直接使用quote_from_bytes()出现的报错

**Comment by samurai00** [comment]
你说的是具体是哪个接口？
可否把具体报错完整贴一下。

我们 SDK 里没有直接用 quote_from_bytes 的地方。在 3.7 测试了 recharge 相关的 6 个接口，也没有发现类似的报错。

版本: 2.7.2

**Comment by sankyson** [comment]
```
def rechargeTest(request):

    params = {
        "user": "user_001",
        "charge": {
            "amount": 10000,
            "channel": "alipay",
            "order_no": str_random(20),
            "subject": "Your subject",
            "body": "Your body",
            "time_expire": int(time.time()) + 3600,
            "client_ip": "127.0.0.1",
            "extra": {}
        },
            # "user_fee": 0,
            # "balance_bonus": {
            #     "amount": 100,
            # },
            # "from_user": "user_002",
        "description": "Your description",
        "metadata": {}
    }

    recharge = pingpp.Recharge.create(**params)
    print(">> create recharge ", recharge)
    return HttpResponse(recharge)
```

你好，上面是调用接口的代码，下面是Traceback信息：

File "C:\Users\sankyson\Desktop\czcServer\models\pay\urlHandler.py" in rechargeTest
  1078.     recharge = pingpp.Recharge.create(**params)

File "C:\Users\sankyson\AppData\Local\Programs\Python\Python37\lib\site-packages\pingpp-2.7.2-py3.7.egg\pingpp\api_resources\abstract\createable_app_based_api_resource.py" in create
  13.         url = cls.class_url(app)

File "C:\Users\sankyson\AppData\Local\Programs\Python\Python37\lib\site-packages\pingpp-2.7.2-py3.7.egg\pingpp\api_resources\abstract\app_based_api_resource.py" in class_url
  34.         return "/v1/apps/%s/%ss" % (quote_plus(app), cls_name)

File "C:\Users\sankyson\AppData\Local\Programs\Python\Python37\lib\urllib\parse.py" in quote_plus
  807.     string = quote(string, safe + space, encoding, errors)

File "C:\Users\sankyson\AppData\Local\Programs\Python\Python37\lib\urllib\parse.py" in quote
  791.     return quote_from_bytes(string, safe)

File "C:\Users\sankyson\AppData\Local\Programs\Python\Python37\lib\urllib\parse.py" in quote_from_bytes
  816.         raise TypeError("quote_from_bytes() expected bytes")

Exception Type: TypeError at /czc.pay.recharge.test/
Exception Value: quote_from_bytes() expected bytes

**Comment by samurai00** [comment]
应该是 没有设置 app_id 

```python
pingpp.app_id = 'app_HHSJD22h444xxx'
```

**Comment by sankyson** [comment]
```
def rechargeTest(request):

    params = {
        "user": "user_001",
        "charge": {
            "amount": 10000,
            "channel": "alipay",
            "order_no": str_random(20),
            "subject": "Your subject",
            "body": "Your body",
            "time_expire": int(time.time()) + 3600,
            "client_ip": "127.0.0.1",
            "extra": {}
        },
            # "user_fee": 0,
            # "balance_bonus": {
            #     "amount": 100,
            # },
            # "from_user": "user_002",
        "description": "Your description",
        "metadata": {}
    }

    recharge = pingpp.Recharge.create(**app=app_id**, **params)
    print(">> create recharge ", recharge)
    return HttpResponse(recharge)
```

可以了，谢谢。全局是已经设置app_id的，大部分接口调用的时候都没有要求重新设置app_id参数的，这里需要在调用recharge接口时加上app_id，pingpp.Recharge.create(app=app_id, **params)，所以sdk在接受参数时判断这个参数是否为空，返回“app_id参数不能为空”这样的提示可能会更好一点。

**Comment by samurai00** [comment]
确实这里需要优化一下。谢谢提醒。
