### ISSUE TITLE
2.0.3版本在Python 3.4中通过pip安装报错

### ISSUE THREAD

**Issue by 0bit** [PingPlusPlus/pingpp-python#4]
`2.0.1`版本可以正常安装，`2.0.3`版本在Python 2.x中安装正常，3.4中不能安装。
在`OS X 10.10`和`Ubuntu Server 14.04`中测试结果一致

测试执行以下命令：
``` bash
mkvirtualenv test_pingpp -p /usr/local/bin/python3.4
workon test_pingpp
pip install pingpp
```

报错信息如下：
```
Collecting pingpp
  Using cached pingpp-2.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-l_wz_8r0/pingpp/setup.py", line 32, in <module>
        from pingpp.version import VERSION
      File "/tmp/pip-build-l_wz_8r0/pingpp/pingpp/__init__.py", line 12, in <module>
        from pingpp.resource import Charge

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-l_wz_8r0/pingpp
```

**Comment by jiezili** [comment]
Encountered the same error

**Comment by lumixiliu** [comment]
谢谢，我们最近更改一下。

**Comment by lumixiliu** [comment]
实在不好意思，之前是我们疏忽了。今天会更新2.0.4的包解决这个问题，已经测试过了，麻烦您稍后更新一下哈：下面是在ubuntu里面的测试结果

root@li610-122:~# pip3 install pingpp
Downloading/unpacking pingpp
  Downloading pingpp-2.0.4.tar.gz (159kB): 159kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pingpp/setup.py) egg_info for package pingpp

Requirement already satisfied (use --upgrade to upgrade): requests>=0.8.8 in /usr/lib/python3/dist-packages (from pingpp)
Installing collected packages: pingpp
  Running setup.py install for pingpp
    Skipping implicit fixer: buffer
    Skipping implicit fixer: idioms
    Skipping implicit fixer: set_literal
    Skipping implicit fixer: ws_comma

Successfully installed pingpp
Cleaning up...

在mac上的测试结果是：
$ pip install pingpp
Collecting pingpp
  Downloading pingpp-2.0.4.tar.gz (159kB)
    100% |████████████████████████████████| 159kB 40kB/s
Collecting requests>=0.8.8 (from pingpp)
  Using cached requests-2.7.0-py2.py3-none-any.whl
Building wheels for collected packages: pingpp
  Running setup.py bdist_wheel for pingpp
  Stored in directory: /Users/edwin/Library/Caches/pip/wheels/76/d8/ee/b87d122e28169a946067a567c475ab3c9b819c1b5b215da3b6
Successfully built pingpp
Installing collected packages: requests, pingpp
Successfully installed pingpp-2.0.4 requests-2.7.0

**Comment by 0bit** [comment]
@lumixiliu 升级了一下，没问题了。多谢。
