### ISSUE TITLE
使用ping++接入微信支付疑问

### ISSUE THREAD

**Issue by stableShip** [PingPlusPlus/pingpp-python#5]
现在我们这边接入了微信的jsapi进行用户网页授权,好友分享等功能,使用到了accesstoken,担心ping++的微信支付会刷新了accesstoken,造成业务逻辑错误?在代码里面也看到了你们获取网页授权的,请问会不会有问题??

**Comment by samurai00** [comment]
取 access_token、jsapi_ticket 这部分是独立的。你这边已经取过 access_token 的话，你可以参考我们的代码，自己重写取 jsapi_ticket 的代码，然后全局缓存起来。
