### ISSUE TITLE
想咨询下Webhooks回调时，签名验证里取JSON排序如何保持的？

### ISSUE THREAD

**Issue by duzhipeng** [PingPlusPlus/pingpp-python#7]
感觉签名是不是缺乏灵活？
Flask下，用request.get_json()得到的JSON数据的键值对排列和POST过来的不一样，导致签名验证也失败，有什么好的方法解决这个问题么？

**Comment by samurai00** [comment]
要取 post 的原始数据、原始字符串，而不是转换过后的数据。
